spring:
  application:
    name: thymeleaf
  thymeleaf:
    cache: false

# DB ??
  datasource:
    driver-class-name: net.sf.log4jdbc.sql.jdbcapi.DriverSpy
    url: jdbc:log4jdbc:oracle:thin:@localhost:1521/xe
    username: springboot
    password: java1234


server:
  port: 8090

# Mybatis ??
mybatis:
  type-aliases-package: com.test.thymeleaf.dto
  mapper-locations: classpath:mapper/*.xml
